/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

import com.itextpdf.text.DocumentException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kemal
 */
public class Malzeme_Stok extends javax.swing.JFrame {

    /**
     * Creates new form Malzeme_Stok
     */
    private int calisanrestoran_id;
    private int calisankullanici_id;
    private int yetki;
    private String R_adi;

    NumberFormat currency = NumberFormat.getCurrencyInstance();

    public Malzeme_Stok(int kullanici_id) {
        initComponents();
        ArrayList<Calisanlar> kullanici = RestoranDB.Kullanicilar.KullanicilariListele(kullanici_id);
        for (Calisanlar item : kullanici) {
            calisanrestoran_id = item.getRestoran_id();
            calisankullanici_id = item.getKullanici_id();
            yetki = item.getYetki();
            jLabel5.setText(item.getCalisan_adi() + " " + item.getCalisan_soyadi());
        }
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.RestoranlariListele(calisanrestoran_id);
        for (Restoranlar item : restoran) {
            R_adi = item.getRestoran_adi();
        }
        restoranlar();
        malzemeler();
        malzemelistelegenel();
        if (yetki == 4) {
            jComboBox1.setEnabled(false);
            jComboBox1.setSelectedItem(R_adi);
        }
    }

    private int restoran_id, malzeme_id, malzeme_ids;
    String Restoran_adi = "";
    private int res = 0;
    private DefaultTableModel model;

    public void restoranlar() {
        jComboBox1.addItem("Tüm Restoranlar");
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.TümRestoranlaricarisizListele();
        for (Restoranlar item : restoran) {
            jComboBox1.addItem(item.getRestoran_adi());
            restoran_id = item.getRestoran_id();
            Restoran_adi = item.getRestoran_adi();
        }
    }

    public void restoranadibul() {
        String ad = jComboBox1.getSelectedItem().toString();
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.RestoranlariListelead(ad);
        for (Restoranlar item : restoran) {
            res = item.getRestoran_id();
        }
    }

    public void malzemeler() {
        ArrayList<Malzeme_Kayit> malzeme = RestoranDB.Malzeme_Kayitlari.MalzemeleriListele();
        for (Malzeme_Kayit item : malzeme) {
            jComboBox2.addItem(item.getMalzeme_adi());
        }
    }

    public void malzemeadibul() {
        String ad = jComboBox2.getSelectedItem().toString();
        ArrayList<Malzeme_Kayit> malzeme = RestoranDB.Malzeme_Kayitlari.MalzemeListelead(ad);
        for (Malzeme_Kayit item : malzeme) {
            malzeme_id = item.getMalzeme_id();
        }
    }

    public void malzemelistele() {
        ArrayList<Malzeme> malzemeler = RestoranDB.Malzemeler.RestoranMalzemeleriListele(res);
        for (Malzeme item : malzemeler) {
            model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[5];
            row[0] = item.getStok_kayit().getMalzeme_adi();
            row[1] = item.getMalzeme_miktar();
            row[2] = currency.format(item.getMalzeme_birim_fiyat());
            row[3] = currency.format(item.getMalzeme_fiyat());
            row[4] = item.getMalzeme_id();
            model.addRow(row);
        }
    }

    public void malzemelistelegenel() {
        try {
            model.getDataVector().removeAllElements();
        } catch (Exception e) {
        }
        ArrayList<Malzeme> malzemeler = RestoranDB.Malzemeler.MalzemeListeleGenel();
        for (Malzeme item : malzemeler) {
            model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[5];
            row[0] = item.getStok_kayit().getMalzeme_adi();
            row[1] = item.getMalzeme_miktar();
            row[2] = currency.format(item.getMalzeme_birim_fiyat());
            row[3] = currency.format(item.getMalzeme_fiyat());
            row[4] = item.getMalzeme_id();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MALZEME STOKLARI");

        jLabel1.setText("Restoran:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme", "Malzeme Miktarı", "Birim Fiyatı", "Toplam", "Malzeme No"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Güncelle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Temizle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("GERİ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Malzeme:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Malzeme Miktarı:");

        jLabel4.setText("Birim Fiyatı:");

        jLabel5.setText("jLabel5");

        jButton6.setText("FATURA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(98, 98, 98)
                .addComponent(jButton2)
                .addGap(73, 73, 73)
                .addComponent(jButton3)
                .addGap(84, 84, 84)
                .addComponent(jButton4)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, 0, 189, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(37, 37, 37)
                        .addComponent(jButton6)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (yetki == 5) {
            YoneticiForm yonetici = new YoneticiForm(calisankullanici_id);
            yonetici.show();
            this.hide();
        } else {
            RestoranYonetimIslem yonetim = new RestoranYonetimIslem(calisankullanici_id);
            yonetim.show();
            this.hide();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().toString() == "Tüm Restoranlar") {
            malzemelistelegenel();
        } else {
            restoranadibul();
            try {
                model.getDataVector().removeAllElements();
            } catch (Exception e) {
            }
            malzemelistele();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        restoranadibul();
        malzemeadibul();
        RestoranDB.Malzemeler.Malzeme_Ekle(malzeme_id, Double.parseDouble(jTextField1.getText()), res, Double.parseDouble(jTextField2.getText()));
        if (model != null) {
            model.getDataVector().removeAllElements();
        }
        malzemelistele();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jComboBox2.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        restoranadibul();
        malzeme_ids = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            model.getDataVector().removeAllElements();
        } catch (Exception e) {
        }
        RestoranDB.Malzemeler.MalzemeGüncelle(malzeme_id, Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), res, malzeme_ids);
        malzemelistele();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        malzemeadibul();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[] noSaveOption = {"Evet", "Hayır"}; // Obje Dizisi Oluşturduk

        String message = "Kullanıcıyı Silmek İstediğinize Emin Misiniz?"; // Verilecek Mesaj

        String title = "Dikkat!!"; // Pencere Başlığı
        int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, noSaveOption, null);

        if (noSave == JOptionPane.YES_OPTION) {
            // Kullanıcı Evet'e Bastıysa
            RestoranDB.Malzemeler.Malzeme_Sil(malzeme_ids);
            model.getDataVector().removeAllElements();
            malzemelistele();

        } else if (noSave == JOptionPane.NO_OPTION) {
            // Kullanıcı Hayır'ya Bastıysa
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int durum = 0;
        ArrayList<Malzeme> malzemeler;
        if (yetki == 5) {
            malzemeler = RestoranDB.Malzemeler.TümMalzemeleriListele();
        } else {
            malzemeler = RestoranDB.Malzemeler.RestoranMalzemeleriListele(calisanrestoran_id);
        }

        for (Malzeme item : malzemeler) {
            if (item.getFatura_durum() == 0) {
                durum = 1;
            }
        }
        if (durum == 1) {
            FATURA_KES fatura = new FATURA_KES(calisankullanici_id);
            fatura.show();
            this.hide();
        } else {
            Object[] noSaveOption = {"TAMAM"}; // Obje Dizisi Oluşturduk

            String message = "Kesilecek Fatura Kalmadı..."; // Verilecek Mesaj

            String title = "Dikkat!!"; // Pencere Başlığı
            int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, noSaveOption, null);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Malzeme_Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Malzeme_Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Malzeme_Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Malzeme_Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Malzeme_Stok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
