/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kemal
 */
public class MenuIslem extends javax.swing.JFrame {

    /**
     * Creates new form MenuIslem
     */
    private int calisanrestoran_id;
    private int calisankullanici_id;
    private int yetki;
    private int urun_id;
    private int restoran_id = 0;
    private String Restoran_adi;
    private String R_adi;

    private int menu_id;

    private DefaultTableModel model;
    NumberFormat currency = NumberFormat.getCurrencyInstance();

    public MenuIslem(int kullanici_id) {
        initComponents();
        ArrayList<Calisanlar> kullanici = RestoranDB.Kullanicilar.KullanicilariListele(kullanici_id);
        for (Calisanlar item : kullanici) {
            calisanrestoran_id = item.getRestoran_id();
            calisankullanici_id = item.getKullanici_id();
            yetki = item.getYetki();
        }
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.RestoranlariListele(calisanrestoran_id);
        for (Restoranlar item : restoran) {
            R_adi = item.getRestoran_adi();
        }
        restoranlar();
        restoranadibul();
        menuleriListele();
        if (yetki == 4) {
            jComboBox2.setEnabled(false);
            jComboBox2.setSelectedItem(R_adi);
        }
    }

    public void menuleriListele() {
        ArrayList<Menu> menu;
        if (yetki == 5) {
            menu = RestoranDB.Menuler.MenuListele(0);
        } else {
            menu = RestoranDB.Menuler.MenuListele(calisanrestoran_id);
        }
        for (Menu item : menu) {
            model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[8];
            row[0] = item.getRestoran().getRestoran_adi();
            row[1] = item.getMenu_adi();
            row[2] = item.getMenu_tarih();
            row[3] = item.getUrunler().getUrunAdi();
            row[4] = item.getUrunler().getUrunAyrinti();
            row[5] = currency.format(item.getUrunler().getUrunUcret());
            row[6] = RestoranDB.menu_TipBul(item.getUrun_tipi());
            row[7] = item.getMenu_id();
            model.addRow(row);
        }
    }

    public void UrunleriYerlestir() {
        ArrayList<Urun> urunlerim = RestoranDB.Urunler.UrunListe(-1, restoran_id);
        for (Urun item : urunlerim) {
            jComboBox4.addItem(item.getUrunAdi());
        }
    }

    public void restoranlar() {
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.TümRestoranlaricarisizListele();
        for (Restoranlar item : restoran) {
            jComboBox2.addItem(item.getRestoran_adi());
            restoran_id = item.getRestoran_id();
            Restoran_adi = item.getRestoran_adi();
        }
    }

    public void restoranadibul() {
        String ad = jComboBox2.getSelectedItem().toString();
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.RestoranlariListelead(ad);
        for (Restoranlar item : restoran) {
            restoran_id = item.getRestoran_id();
        }
    }

    public void Urun_idbul() {
        String ad = jComboBox4.getSelectedItem().toString();
        ArrayList<Urun> urun = RestoranDB.Urunler.UrunListelead(ad, restoran_id);
        for (Urun item : urun) {
            urun_id = item.getUrunId();
        }
    }

    public void adkontrol() {
        if (RestoranDB.Menuler.MenuAd(restoran_id) > 0) {
            jTextField1.setEnabled(false);
            ArrayList<Menu> menu = RestoranDB.Menuler.MenuListele(restoran_id);
            for (Menu item : menu) {
                jTextField1.setText(item.getMenu_adi());
            }
        } else {
            jTextField1.setEnabled(true);
            jTextField1.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENÜ");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restoran Adı", "Menu Adi", "Tarih", "Ürün Adı", "Ürün Ayrıntı", "Ücret", "Tip", "ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ürün:");

        jLabel2.setText("Menü Adı:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Restoran:");

        jButton1.setText("EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Güncelle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SİL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("TEMİZLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("GERİ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ürün Tipi:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Başlangıç", "Ana Yemek", "Tatlı", "İçecek" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });

        jButton6.setText("Menü Sil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Menü Aç");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton7)
                                            .addComponent(jButton6))
                                        .addGap(24, 24, 24))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(102, 102, 102)
                .addComponent(jButton2)
                .addGap(102, 102, 102)
                .addComponent(jButton3)
                .addGap(125, 125, 125)
                .addComponent(jButton4)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(17, 17, 17)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (yetki == 5) {
            YoneticiForm yonetim = new YoneticiForm(calisankullanici_id);
            yonetim.show();
            this.hide();
        } else {
            RestoranYonetimIslem resyonetim = new RestoranYonetimIslem(calisankullanici_id);
            resyonetim.show();
            this.hide();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (model != null) {
            model.getDataVector().removeAllElements();
        }
        Urun_idbul();
        restoranadibul();
        RestoranDB.Menuler.MenuyeUrunEkle(jTextField1.getText(), String.valueOf(RestoranDB.menu_Tip((String) jComboBox3.getSelectedItem())), urun_id, restoran_id);
        menuleriListele();
        adkontrol();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jComboBox4.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        jLabel5.setIcon(null);
        jLabel5.setText("");
        QR barkod = new QR();
        barkod.QRread(jLabel5, "QR\\" + jTextField1.getText() + jComboBox2.getSelectedItem() + ".png");
        adkontrol();
        jComboBox4.removeAllItems();
        restoranadibul();
        UrunleriYerlestir();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
        Urun_idbul();
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        Urun_idbul();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Urun_idbul();
        restoranadibul();
        menu_id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 7);
        jComboBox2.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        jComboBox4.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3));
        jComboBox3.setSelectedIndex(RestoranDB.menu_Tip(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString()));
        jTextField1.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[] noSaveOption = {"Evet", "Hayır"}; // Obje Dizisi Oluşturduk

        String message = "Menüden Ürünü Silmek İstediğinize Emin Misiniz?"; // Verilecek Mesaj

        String title = "Dikkat!!"; // Pencere Başlığı
        int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, noSaveOption, null);

        if (noSave == JOptionPane.YES_OPTION) {
            // Kullanıcı Evet'e Bastıysa
            RestoranDB.Menuler.MenuUrunSil(menu_id);
            model.getDataVector().clear();
            menuleriListele();
            if (RestoranDB.Menuler.MenuAd(restoran_id) <= 0) {
                Resim_Islem.ResimSil("menüler\\" + jTextField1.getText() + jComboBox2.getSelectedItem() + ".pdf");
            }

        } else if (noSave == JOptionPane.NO_OPTION) {
            // Kullanıcı Hayır'ya Bastıysa
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RestoranDB.Menuler.MenuyeUrunGuncelle(jTextField1.getText(), RestoranDB.menu_Tipstring(String.valueOf(jComboBox3.getSelectedItem())), urun_id, restoran_id, menu_id);
        model.getDataVector().clear();
        menuleriListele();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Object[] noSaveOption = {"Evet", "Hayır"}; // Obje Dizisi Oluşturduk

        String message = "Menüyü Silmek İstediğinize Emin Misiniz?"; // Verilecek Mesaj

        String title = "Dikkat!!"; // Pencere Başlığı
        int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, noSaveOption, null);

        if (noSave == JOptionPane.YES_OPTION) {
            // Kullanıcı Evet'e Bastıysa
            model.getDataVector().clear();
            RestoranDB.Menuler.MenuSil(restoran_id);
            Resim_Islem.ResimSil("menüler\\" + jTextField1.getText() + jComboBox2.getSelectedItem() + ".pdf");
            menuleriListele();

        } else if (noSave == JOptionPane.NO_OPTION) {
            // Kullanıcı Hayır'ya Bastıysa
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if (RestoranDB.Menuler.MenuAd(restoran_id) <= 0) {
            Object[] noSaveOption = {"Tamam"}; // Obje Dizisi Oluşturduk

            String message = "Menüde Eleman Yok"; // Verilecek Mesaj

            String title = "Dikkat!!"; // Pencere Başlığı
            int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, noSaveOption, null);
        } else {
            PDFTABLE menu = new PDFTABLE("menüler\\" + jTextField1.getText() + jComboBox2.getSelectedItem());
            try {
                try {
                    menu.addQR("QR\\" + jTextField1.getText() + jComboBox2.getSelectedItem() + ".png");
                } catch (BadElementException ex) {
                    Logger.getLogger(MenuIslem.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MenuIslem.class.getName()).log(Level.SEVERE, null, ex);
                }
                menu.dosyabaslik(jTextField1.getText());
                menu.dosyabaslik("");
                menu.dosyabaslik("BAŞLANGIÇLAR");
                menu.createmenu(restoran_id, "0");
                menu.dosyabaslik("");
                menu.dosyabaslik("ANA YEMEKLER");
                menu.createmenu(restoran_id, "1");
                menu.dosyabaslik("");
                menu.dosyabaslik("TATLILAR");
                menu.createmenu(restoran_id, "2");
                menu.dosyabaslik("");
                menu.dosyabaslik("İÇECEKLER");
                menu.createmenu(restoran_id, "3");
                menu.dosyakapa();
            } catch (DocumentException ex) {
                Logger.getLogger(MenuIslem.class.getName()).log(Level.SEVERE, null, ex);
            }
            QR barkod = new QR();
            barkod.QRWrite("QR\\" + jTextField1.getText() + jComboBox2.getSelectedItem());
            barkod.QRread(jLabel5, "QR\\" + jTextField1.getText() + jComboBox2.getSelectedItem() + ".png");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        ArrayList<Menu> menu;
        if (yetki == 5) {
            menu = RestoranDB.Menuler.MenuListeleAra(0, jTextField2.getText());
        } else {
            menu = RestoranDB.Menuler.MenuListeleAra(calisanrestoran_id, jTextField2.getText());
        }

        for (Menu item : menu) {
            model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[8];
            row[0] = item.getRestoran().getRestoran_adi();
            row[1] = item.getMenu_adi();
            row[2] = item.getMenu_tarih();
            row[3] = item.getUrunler().getUrunAdi();
            row[4] = item.getUrunler().getUrunAyrinti();
            row[5] = currency.format(item.getUrunler().getUrunUcret());
            row[6] = RestoranDB.menu_TipBul(item.getUrun_tipi());
            row[7] = item.getMenu_id();
            model.addRow(row);
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuIslem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
