/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

import com.itextpdf.text.DocumentException;
import java.awt.Font;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Kemal
 */
public class RestoranCari extends javax.swing.JFrame {

    /**
     * Creates new form RestoranCari
     */
    private int calisanrestoran_id;
    private int calisankullanici_id;
    NumberFormat currency =NumberFormat.getCurrencyInstance();

    public RestoranCari(int kullanici_id) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ArrayList<Calisanlar> kullanici = RestoranDB.Kullanicilar.KullanicilariListele(kullanici_id);
        for (Calisanlar item : kullanici) {
            calisanrestoran_id = item.getRestoran_id();
            calisankullanici_id = item.getKullanici_id();
        }
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.TümRestoranlaricarisizListele();
        for (Restoranlar item : restoran) {
            yarat(item.getRestoran_adi(), item.getRestoran_id());
        }
    }

    int x = 30, y = 50, w = 120, h = 40;

    public void uret(String labelname, String tittle, int res_id) {
        JLabel label = new JLabel(tittle);
        Font font = new Font("Arial Black", Font.PLAIN, 13);
        label.setFont(font);
        label.setName("restoranlar");
        label.setBounds(x, y, w, h);
        JLabel labelson = new JLabel(tittle);
        labelson.setName(labelname);
        labelson.setBounds(x + 350, y, w, h);
        add(labelson);
        add(label);
        y += 40;
        if (y > 810) {
            y = 0;
            y += 40;
            x += 600;
        }
        int gelir = 0, gider = 0;
        ArrayList<Cari> cari = RestoranDB.Cariler.CariListele(res_id);

        for (Cari item : cari) {
            gelir += item.getCari_gelir();
            gider += item.getCari_gider();
        }
        if (("gelir" + String.valueOf(res_id)).equals(labelname)) {
            labelson.setText(String.valueOf(this.currency.format(gelir)));
        } else if (("gider" + String.valueOf(res_id)).equals(labelname)) {
            labelson.setText(String.valueOf(this.currency.format(gider)));
        } else if (("kdv" + String.valueOf(res_id)).equals(labelname)) {
            labelson.setText(String.valueOf(this.currency.format(gelir * 0.18)));
        } else {
            labelson.setText(String.valueOf(this.currency.format(RestoranDB.Cariler.karHesapla(res_id))));
        }
    }
    int ty = -20, tx = 120, tw = 300;

    public void baslikuret(String restoran_adi) {
        JLabel label = new JLabel(restoran_adi);
        Font font = new Font("Arial Black", Font.PLAIN, 18);
        label.setFont(font);
        label.setName("baslik");
        label.setBounds(tx, ty, tw, 150);
        ty += 160;
        if (ty > 810) {
            ty = -10;
            tx += 600;
            tw += 120;
            label.setBounds(tx, ty, tw, 150);
            ty += 160;
        }
        add(label);
    }

    public void yarat(String restoran_adi, int restoran_id) {
        baslikuret(restoran_adi);
        uret("gelir" + String.valueOf(restoran_id), "Toplam Gelir:", restoran_id);
        uret("gider" + String.valueOf(restoran_id), "Toplam Gider:", restoran_id);
        uret("kdv" + String.valueOf(restoran_id), "KDV:", restoran_id);
        uret("kar" + String.valueOf(restoran_id), "NET KAR::", restoran_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HESAP DURUMU");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("HESAPLAR");

        jButton1.setText("GERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RAPOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 248, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        YoneticiForm yonetim = new YoneticiForm(calisankullanici_id);
        yonetim.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PDFTABLE tablo = new PDFTABLE("RAPOR");
        try {
            tablo.dosyabaslik("RESTORAN HESAP RAPOR");
        } catch (DocumentException ex) {
            Logger.getLogger(OptimizasyonIslem.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablo.createICariReport(0);
        tablo.dosyakapa();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoranCari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoranCari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoranCari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoranCari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RestoranCari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
