/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kemal
 */
public class RestoranKapa extends javax.swing.JFrame {

    /**
     * Creates new form RestoranKapa
     */
    private int calisanrestoran_id;
    private int calisankullanici_id;

    public RestoranKapa(int kullanici_id) {
        initComponents();
        ArrayList<Calisanlar> kullanici = RestoranDB.Kullanicilar.KullanicilariListele(kullanici_id);
        for (Calisanlar item : kullanici) {
            calisanrestoran_id = item.getRestoran_id();
            calisankullanici_id = item.getKullanici_id();
        }
        RestoranlariListele();
    }

    private DefaultTableModel model;
    private int restoran_id, ulke_id, il_id, ilce_id;
    private String restoran_ad, restoran_adres, restoran_tel, restoran_vd;
    private Double gelir, gider;

    NumberFormat currency = NumberFormat.getCurrencyInstance();

    public void RestoranlariListele() {
        ArrayList<Restoranlar> restoranlar = RestoranDB.Restoranlarim.TümRestoranlaricarisizListele();
        for (Restoranlar item : restoranlar) {
            model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[10];
            row[0] = item.getRestoran_adi();
            row[1] = item.getRestoran_adres();
            row[2] = item.getRestoran_tel();
            row[3] = item.getRestoran_vd();
            row[4] = RestoranDB.Ulkeler.Ulke_Listele(item.getUlke_id());
            row[5] = RestoranDB.Iller.Il_Listele(item.getIl_id());
            row[6] = RestoranDB.Ilceler.Ilce_Listele(item.getIlce_id());
            row[7] = currency.format(RestoranDB.Restoranlarim.RestoranHesaplama(item.getRestoran_id(), "gelir"));
            row[8] = currency.format(RestoranDB.Restoranlarim.RestoranHesaplama(item.getRestoran_id(), "gider"));
            row[9] = currency.format(RestoranDB.Restoranlarim.RestoranHesaplama(item.getRestoran_id(), "kar"));
            model.addRow(row);
        }
    }

    public void restoranadibul() {
        String ad = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        ArrayList<Restoranlar> restoran = RestoranDB.Restoranlarim.RestoranlariListelead(ad);
        for (Restoranlar item : restoran) {
            restoran_id = item.getRestoran_id();
        }
    }

    public void ulkeidbul() {
        String ulke = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        ArrayList<Ulke> ulkegelen = RestoranDB.Ulkeler.UlkeListelead(ulke);
        for (Ulke item : ulkegelen) {
            ulke_id = item.getId();
        }
    }

    public void Ilidbul() {
        String il = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        ArrayList<Il> ilgelen = RestoranDB.Iller.IlListelead(il);
        for (Il item : ilgelen) {
            il_id = item.getId();
        }
    }

    public void Ilceidbul() {
        String ilce = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        ArrayList<Ilce> ilcegelen = RestoranDB.Ilceler.IlceListelead(ilce);
        for (Ilce item : ilcegelen) {
            ilce_id = item.getId();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESTORAN KAPA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restoran Adı", "Restoran Adresi", "TEL", "V.D.", "Ülke", "İl", "İlçe", "Gelir", "Gider", "Kar"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Kapat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GERİ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        YoneticiForm yonetici = new YoneticiForm(calisankullanici_id);
        yonetici.show();
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        restoranadibul();
        restoran_ad = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        restoran_adres = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        restoran_tel = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        restoran_vd = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        ulkeidbul();
        Ilidbul();
        Ilceidbul();
        gelir = Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        gider = Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object[] noSaveOption = {"Evet", "Hayır"}; // Obje Dizisi Oluşturduk

        String message = "Seçili Restoranı Kapatmak İstediğinize Emin Misiniz?"; // Verilecek Mesaj

        String title = "Dikkat!!"; // Pencere Başlığı
        int noSave = JOptionPane.showOptionDialog(null, message, title, JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, noSaveOption, null);

        if (noSave == JOptionPane.YES_OPTION) {
            // Kullanıcı Evet'e Bastıysa
            RestoranDB.Kapanan_Restoranlar.Restoran_Kapa(restoran_ad, restoran_adres, restoran_tel, restoran_vd, gelir, gider, ulke_id, il_id, ilce_id);
            RestoranDB.Restoranlarim.RestoranSil(restoran_id);
            RestoranDB.Cariler.CariSil(restoran_id);
            if (model != null) {
                model.getDataVector().removeAllElements();
            }
            RestoranlariListele();

        } else if (noSave == JOptionPane.NO_OPTION) {
            // Kullanıcı Hayır'ya Bastıysa
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoranKapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoranKapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoranKapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoranKapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RestoranKapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
